"""
Shadow Mode Execution Harness.
Executes agent workflows in non-publishing observation mode to establish baseline accuracy
without mutating production state or publishing deal broadcasts.
"""

import logging
import time
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field

from loot_brain.harness.tools import ToolRegistry, SideEffectLevel
from loot_brain.harness.checkpoints import CheckpointStore, TaskExecutionTrace

logger = logging.getLogger(__name__)


class ShadowExecutionReport(BaseModel):
    """Report generated by shadow mode execution."""
    task_id: str
    agent_id: str
    planned_actions: Dict[str, Any] = Field(default_factory=dict)
    suppressed_side_effects: Dict[str, Any] = Field(default_factory=dict)
    would_publish: bool = False
    execution_time_ms: float = 0.0
    shadow_mode: bool = True


class ShadowRunner:
    """
    Executes agent pipelines in Shadow Mode.
    Observes, plans, scores, and verifies deal payloads, but suppresses side-effect operations.
    """

    def __init__(self, tool_registry: ToolRegistry, checkpoint_store: CheckpointStore):
        self.tool_registry = tool_registry
        self.checkpoint_store = checkpoint_store

    def run_shadow_deal_pipeline(self, task_id: str, raw_deal_data: Dict[str, Any]) -> ShadowExecutionReport:
        """
        Executes deal intelligence pipeline in non-mutating Shadow Mode.
        """
        start_time = time.time()
        logger.info(f"[ShadowRunner] Initiating Shadow Mode run for task '{task_id}'...")

        # 1. Execute deal scoring tool (LOW_RISK)
        score_res = self.tool_registry.execute(
            tool_name="deal.score",
            agent_id="shadow_agent",
            kwargs={
                "price": raw_deal_data.get("price", 0.0),
                "mrp": raw_deal_data.get("mrp", 0.0),
                "title": raw_deal_data.get("title", ""),
                "is_verified_low": raw_deal_data.get("is_verified_low", True),
            },
        )

        # 2. Check semantic deduplication (READ_ONLY)
        dedup_res = self.tool_registry.execute(
            tool_name="dedup.check",
            agent_id="shadow_agent",
            kwargs={"title": raw_deal_data.get("title", "")},
        )

        # 3. Simulate Affiliate Link Conversion (LOW_RISK)
        aff_res = self.tool_registry.execute(
            tool_name="affiliate.convert",
            agent_id="shadow_agent",
            kwargs={"url": raw_deal_data.get("url", "https://amazon.in/dp/EXAMPLE")},
        )

        # Determine if deal would be published under production policies
        score = score_res.data.get("deal_score", 0.0) if score_res.success and score_res.data else 0.0
        is_dup = dedup_res.data.get("is_duplicate", False) if dedup_res.success and dedup_res.data else False
        would_publish = (score >= 60.0) and (not is_dup)

        duration = (time.time() - start_time) * 1000

        report = ShadowExecutionReport(
            task_id=task_id,
            agent_id="shadow_agent",
            planned_actions={
                "score_res": score_res.data,
                "dedup_res": dedup_res.data,
                "affiliate_res": aff_res.data,
            },
            suppressed_side_effects={
                "telegram.publish": {
                    "suppressed": True,
                    "target_channel": "@LootRaidersDeals",
                    "payload_title": raw_deal_data.get("title", ""),
                }
            },
            would_publish=would_publish,
            execution_time_ms=duration,
        )

        logger.info(f"[ShadowRunner] Task '{task_id}' Shadow Complete: Would Publish={would_publish} ({duration:.1f}ms)")
        return report
